package tw.newxe.einkcamera;

import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.os.Bundle;
import android.view.WindowManager;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;

/**
 * Static "About" screen reachable from the more-features sidebar menu.
 *
 * Apache 2.0 §4 requires this fork to retain the upstream copyright/license and,
 * for a derivative work, to surface the attribution notices somewhere the user
 * can read them. The repo-level LICENSE covers the source distribution; this
 * screen satisfies the "display generated by the Derivative Works" clause and
 * also credits the third-party libraries (uvccamera/saki, ZXing, ML Kit). The
 * toolbar / launcher glyphs are this fork's own artwork, so they need no
 * third-party attribution.
 */
public class AboutActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        // Match MainActivity's immersive full-screen look: draw edge to edge with
        // the status bar hidden and a translucent nav bar, so the white About
        // screen fills the whole display like the camera screen does.
        EdgeToEdge.enable(this);
        var flags = WindowManager.LayoutParams.FLAG_FULLSCREEN | WindowManager.LayoutParams.FLAG_TRANSLUCENT_NAVIGATION;
        getWindow().setFlags(flags, flags);
        setContentView(R.layout.activity_about);

        TextView version = findViewById(R.id.tv_about_version);
        version.setText(getString(R.string.about_version, getVersionName()));

        ImageView back = findViewById(R.id.btn_about_back);
        back.setOnClickListener(v -> finish());
    }

    private String getVersionName() {
        try {
            PackageInfo info = getPackageManager().getPackageInfo(getPackageName(), 0);
            return info.versionName != null ? info.versionName : "";
        } catch (PackageManager.NameNotFoundException e) {
            // Own package is always installed; this branch is effectively unreachable.
            return "";
        }
    }
}
